spring:
  application:
    name: service-feign
server:
  port: 8095

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

feign:
  hystrix:
    enabled: true