server:
  port: 8096
spring:
  cloud:
    gateway:
      routes:
        - id: service-client
          uri: lb://EUREKA-CLIENT
          predicates:
            - Path=/client/**
          filters:
            - StripPrefix=1

        - id: limit_route
          uri: http://httpbin.org:80/get
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@uriKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 3
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  application:
    name: gateway-limiter
  redis:
    database: 1
    host: 172.29.1.123
    port: 6379
    password: wolwo123
    timeout: 3000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

